return {
["workshop-1991746508"] = { configuration_options={ Language="A", ShowBuff=true }, enabled = true },
["workshop-1699194522"] = { configuration_options={ Skillbadge=true }, enabled = true },
["workshop-2019613520"] = {
configuration_options={
      ["1"]=0,
      ["2"]=0,
      ["3"]=0,
      ["4"]=true,
      FanWei=true,
      Gongji=true,
      PengZhuang=true,
      Xueliang=true,
      aaaaaaaaaaa=0,
      caiji=true,
      diaoluo=true,
      gensui=true,
      quanshijian=true,
      quanxian=false,
      suiyibaifang=false,
      xiayu=false,
      yongyenew=3,
      ["万物倍数"]=20,
      ["万物大小"]=false,
      ["人类倍数"]=20,
      ["大型生物倍数"]=20,
      ["小型生物倍数"]=30,
      ["树木倍数"]=20,
      ["树木大小"]=false,
      ["植物倍数"]=20,
      ["植物大小"]=false,
      ["池塘倍数"]=20,
      ["池塘大小"]=true,
      ["海上事物"]=false,
      ["海上倍数"]=20,
      ["海难倍数"]=20,
      ["海难兼容"]=false,
      ["玩家人类"]=false,
      ["玩家建筑"]=false,
      ["玩家建筑倍数"]=20,
      ["神话倍数"]=20,
      ["神话兼容"]=true,
      ["衣柜箱子"]=false,
      ["衣柜箱子倍数"]=20,
      ["随机建筑开关"]=true 
    },
    enabled=true 
},
["workshop-2299268435"] = {
    configuration_options={
      ["1"]=0,
      ["2"]=0,
      ["3"]=0,
      ["3333"]=0,
      ["9"]=0,
      Figure=2,
      Nightmare=1.4,
      Resist=false,
      aw_thirst=1,
      aw_thirst_max=250,
      aw_thirst_speed=5,
      coffee_power=3,
      coffee_time=70,
      craft_bag=0,
      gen_coffe=1.2,
      gen_holes=0.7,
      gen_tea=1.2,
      gen_wheat=1.5,
      gengduojineng=true,
      kanpusi=false,
      kunnanmoshi=false,
      language_cfg=0,
      no_regenerate=false,
      no_rollback=false,
      waterwell_wait=30,
      yincangtianshu=false,
      yincangxiaoditu=false,
      yincangxueliang=false,
      ["克雷官方难度增强"]=false,
      ["极限模式"]=false,
      ["神话加强"]=true 
    },
    enabled=true 
},
["workshop-2591636844"] = { configuration_options={ language="zhs" }, enabled = true },
["workshop-375850593"] = { enabled = true },
["workshop-375859599"] = { enabled = true },
["workshop-378160973"] = { enabled = true },
["workshop-462434129"] = { enabled = true },
["workshop-2287303119"] = { enabled = true },
["workshop-599498678"] = { enabled = true },
["workshop-1595631294"] = { enabled = true },
["workshop-1216718131"] = { enabled = true },
["workshop-2564938022"] = { enabled = true },
}



