site_name: MLSG中文手册
##site_favicon: "docs/favicon.ico"
site_description: "MLSG翼龙面板-中文开服手册"
site_url: https://manual.mr-leaves.com
nav:
  - 1.手册简介: index.md
  - 2.注册登录: 0-serversignup.md
  - 3.基本操作: 1-serverbasics.md
  - 4.进阶操作:
      - 2-serveradvanced/index.md
      - 邀请子用户管理: 2-serveradvanced/subuser.md
      - 重装游戏服务器: 2-serveradvanced/reinstall.md
      - 创建服务器计划: 2-serveradvanced/plan.md
      - SFTP传输大文件: 2-serveradvanced/filetransfer.md
      - Steam公开检查: 2-serveradvanced/steamcheck.md
  - 5.游戏教程: 
      - 3-servergames/index.md
      - 我的世界（Minecraft）: 3-servergames/minecraft.md
      - 饥荒联机版（Dont Strave）: 3-servergames/dontstarve.md
      - 腐蚀/部落（Rust）: 3-servergames/rust.md
      - 森林之子（Son of Forest）: 3-servergames/sof.md
      - 方舟生存进化（ARK）: 3-servergames/ark.md
      - 雨中冒险2（RoR2）: 3-servergames/ror2.md
      - 英灵神殿（Valheim）: 3-servergames/valheim.md
      - 反恐精英（Counter Strike）: 3-servergames/cs.md
      - 僵毁（Project Zombiod）: 3-servergames/pz.md
  - 6.关于我们: about.md

theme:
  name: "material"
  language: zh
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.share
    - navigation.footer
    - navigation.indexes
    - navigation.prune
    - navigation.top
    

plugins:
  - search
  - tags

extra_css:
  - style/extra.css


extra:
  analytics: 
    provider: google
    property: G-WV00ZV20JF
    feedback:
      title: 以上的内容有用吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 非常有用
          data: 1
          note: >-
            感谢您的反馈！
        - icon: material/emoticon-sad-outline
          name: 有待进步
          data: 0
          note: >- 
            感谢您的反馈！帮助我们改进文档，您可以参与我们的<a href="https://github.com/Mr-Leaves-Server-Group/Manual" target="_blank" rel="noopener">Github项目</a>提供更多改进。
    
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/KenRen98/MLSG-Manual-Pages
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/dexuan-ren-b41a9258/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jYHzsy4hAB

  generator: false
  

copyright: Copyright &copy;  2023 MLSG

