site_name: MLSG中文手册
##site_favicon: "docs/favicon.ico"
site_description: "MLSG翼龙面板-中文开服手册"
site_url: https://manual.mr-leaves.com/
nav:
  - 一.手册简介: index.md
  - 二.注册登录: 1.0-serversignup.md
  - 三.基本操作: 1.1-serverbasics.md
  - 四.进阶操作: 1.2-serveradvanced.md
  - 五.具体游戏: 1.3-servergames.md
  - 六.关于我们: about.md

theme:
  name: "material"
  language: zh
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.share
    - navigation.sections
    - navigation.footer
    

plugins:
  - search
  - tags

extra_css:
  - style/extra.css


extra:
  analytics: 
    provider: google
    property: G-WV00ZV20JF
    feedback:
      title: 以上的内容有用吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 非常有用
          data: 1
          note: >-
            感谢您的反馈！
        - icon: material/emoticon-sad-outline
          name: 有待进步
          data: 0
          note: >- 
            感谢您的反馈！帮助我们改进文档，您可以参与我们的<a href="https://github.com/KenRen98/MLSG-Manual-Pages" target="_blank" rel="noopener">Github项目</a>提供更多改进。
    
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/KenRen98/MLSG-Manual-Pages
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/dexuan-ren-b41a9258/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jYHzsy4hAB

  generator: false
  

copyright: Copyright &copy;  2023 MLSG

